name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  ci:
    name: CI Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/node-ci@v3
      - uses: actalog/dockerfile-ci@v2

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
